### ISSUE TITLE
Provide the file of pre-trained models on ImageNet?

### ISSUE THREAD

**Issue by Openning07** [maple-research-lab/AET#1]
Hello, Guo-Jun. Thanks for your great work of AET and making your code available.
Can you also provide the file of **pre-trained models on ImageNet** for the convenience of experiments?
Thank you again for your valuable attention.

**Comment by z331565360** [comment]
Thanks for your request! We just prov

> Hello, Guo-Jun. Thanks for your great work of AET and making your code available.
> Can you also provide the file of **pre-trained models on ImageNet** for the convenience of experiments?
> Thank you again for your valuable attention.

**Comment by z331565360** [comment]
> Hello, Guo-Jun. Thanks for your great work of AET and making your code available.
> Can you also provide the file of **pre-trained models on ImageNet** for the convenience of experiments?
> Thank you again for your valuable attention.

Thanks for your request! We just provided the pre-trained models on ImageNet. Please find the link in README.
